### ISSUE TITLE
Path of the Persistent object created in the Trusted Application of Secure Storage example

### ISSUE THREAD

**Issue by gunaMect** [linaro-swg/optee_examples#106]
Hi, I have been trying out the example, secure_storage -> I need to know the path of the Object being created.
I am using virtual machine Linux setup for QemuV8 environment.

https://github.com/linaro-swg/optee_examples/blob/378dc0db2d5dd279f58a3b6cb3f78ffd6b165035/secure_storage/ta/secure_storage_ta.c#L156C11-L156C11

It gets the object id from the Client application as Object#1 & Object#2 -> https://github.com/linaro-swg/optee_examples/blob/378dc0db2d5dd279f58a3b6cb3f78ffd6b165035/secure_storage/host/main.c#L172  https://github.com/linaro-swg/optee_examples/blob/378dc0db2d5dd279f58a3b6cb3f78ffd6b165035/secure_storage/host/main.c#L173

Here, I need to know the exact path in the REE file system. Is it available in the /data/tee path? 

Also, is it possible to provide an absolute path of my own to store the object? Thanks.

**Comment by jenswi-linaro** [comment]
The files are stored under `/data/tee`, but they are just numbered from `0` and upwards. The file `dirf.db` contains a list of all the files and mappings to the object ids. All the files are encrypted as described at https://optee.readthedocs.io/en/latest/architecture/secure_storage.html#tee-file-structure-in-linux-file-system
