### ISSUE TITLE
Example for TA - TA communication

### ISSUE THREAD

**Issue by gunaMect** [linaro-swg/optee_examples#108]
Hi,

I have tried out the example of [Secure_Storage](https://github.com/linaro-swg/optee_examples/tree/master/secure_storage). With this example, I can store my data to the secure storage, which I verified in the /data/tee folder.

Is there any possibility to achieve TA - TA communication. Here, my use case is to transfer data from one TA to another TA.

If yes, can you share the example for the same? Thanks.

**Comment by jforissier** [comment]
Hi @gunaMect,

For TA-TA communication, one would typically use `TEE_OpenTASession()` etc. see https://github.com/OP-TEE/optee_os/blob/4.0.0/lib/libutee/include/tee_internal_api.h#L73. By design, a TA can **not** open secure storage created by another TA.

**Comment by etienne-lms** [comment]
Maybe having an example of TA-to-TA communication in optee_examples would help.
If anyone is interested, contributions are welcome.

**Comment by gunaMect** [comment]
I will try to create a simple example for TA-TA communication and create a PR.
