### ISSUE TITLE
Is there a SM4 CA call to the TA side demo implementation?

### ISSUE THREAD

**Issue by hallowsman** [linaro-swg/optee_examples#114]
请问有没有sm4的ca调用ta侧demo实现呢？

**Comment by jbech-linaro** [comment]
The people active here doesn't understand your language, please write in English.

**Comment by hallowsman** [comment]
Is there a SM4 CA call to the TA side demo implementation?

**Comment by hallowsman** [comment]
> Is there a SM4 CA call to the TA side demo implementation?

**Comment by hallowsman** [comment]
> The people active here doesn't understand your language, please write in English.

Is there a SM4 CA call to the TA side demo implementation?

**Comment by hallowsman** [comment]
> The people active here doesn't understand your language, please write in English.

Is there a SM4 CA call to the TA side demo implementation?

**Comment by jenswi-linaro** [comment]
No, I don't think so. But SM4 is also a block cipher like AES so the AES example might be good enough for a start.
