### ISSUE TITLE
How can I see log messages generated by Trusted Application

### ISSUE THREAD

**Issue by aim2nasa** [linaro-swg/optee_examples#15]
Through the examples(ex, helloWorld), I could see some log messages generated by the host application. But I have no idea at the moment in what way I could possibly see logs which are generated by TA, something like below.

```
void TA_DestroyEntryPoint(void)
{
	DMSG("has been called");
}
```

Because TA is running in trustzone,  there must be some special method to be able to see logs which TA generates, I think.

Currently I'm using rpi3 and in the document for [it](https://github.com/OP-TEE/build/blob/master/docs/rpi3.md#6-openocd-and-jtag), seems that some jtag cable and uart connections are required as a HW must and for software, OpenOCD etc.

I'm not fluent in embedded environment, so I'm curious the method described in the [document](https://github.com/OP-TEE/build/blob/master/docs/rpi3.md#6-openocd-and-jtag) is the best or recommended way to see the logs which TA creates?

Hope some guide on this.

**Comment by jbech-linaro** [comment]
Hi,

As an example if I run the HOTP example TA I can see:
```bash
...
D/TC:0 console_itr_cb:150 cpu 0: got 0x3
D/TC:0 ta_load:316 ELF load address 0x101000
D/TA:  register_shared_key:147 Got shared key 12345678901234567890 (20 bytes).
D/TA:  get_hotp:179 HOTP is: 755224
....
```
`D/TC` comes from D (DEBUG) / TC (TEE Core).
and 
`D/TA` comes from D (DEBUG) / TA (Trusted Application), i.e., this is a `DMSG` as you are asking for.

For more details about the prefixes, please see [this](https://github.com/OP-TEE/optee_os/commit/546291f4de9b76fb6c5ed4dbdbe685a9805cad2a) commit.

**Comment by jforissier** [comment]
...plus make sure `CFG_TEE_TA_LOG_LEVEL=3` (or higher) because 3 is the level for debug traces.

**Comment by aim2nasa** [comment]
Thanks for all your comments.

- With regard to the hardware required in monitoring logs.
At the moment, I have nothing but usb-to-serial cable.
Is it inevitable to be equipped with JTAG hardware to see the logs which TA generates? 
or Is it possible only with usb-to serial connection?

**Comment by jforissier** [comment]
You don't need JTAG to see the TA logs. They are sent to a serial port.

**Comment by aim2nasa** [comment]
@jforissier Excellent!
Appreciate your help.

**Comment by aim2nasa** [comment]
I'm leaving my TA log result for future reference of someone.

`
root@linaro-developer:/bin# ./optee_example_hello_world
D/TC:0 tee_ta_init_pseudo_ta_session:292 Lookup pseudo TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b
D/TC:0 tee_ta_init_user_ta_session:636 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (Secure Storage TA)
D/TC:0 tee_ta_init_user_ta_session:636 Lookup user TA 8aaaf200-2450-11e4-abe2-0002a5d5c51b (REE)
D/TC:0 ta_load:316 ELF load address 0x40001000
D/TA:  TA_CreateEntryPoint:39 has been called
F/TA:  tee_user_mem_alloc:343: Allocate: link:[0x400130a0], buf:[0x400130c0:32]
D/TA:  TA_OpenSessionEntryPoint:68 has been called
I/TA:  Hello World!
InvokD/TA:  dec_value:125 has been called
inI/TA:  Got value: 42 from NW
g I/TA:  Decrease value to: 41
TA tD/TC:0 tee_ta_close_session:402 tee_ta_close_session(0x8483ca0)
o iD/TC:0 tee_ta_close_session:421 Destroy session
ncrI/TA:  Goodbye!
emenF/TA:  tee_user_mem_free:442: Free: link:[0x400130a0], buf:[0x400130c0:32]
t 4D/TA:  TA_DestroyEntryPoint:50 has been called
D/TC:0 tee_ta_close_session:447 Destroy TA ctx

TA incremented value to 41
root@linaro-developer:/bin#
`
