### ISSUE TITLE
Is dynamic link libraries supported with the ta_dev_kit

### ISSUE THREAD

**Issue by kevin-peng-hao** [linaro-swg/optee_examples#16]
If I'd like to build a library with the ta_dev_kit, I think by default it is a static library, right?
I don't think dynamic link libraries are supported?

**Comment by jforissier** [comment]
Correct.

**Comment by kevin-peng-hao** [comment]
Er...Why is it not supported?

**Comment by jforissier** [comment]
Because, no one has written the code in OP-TEE to load dynamically-linked TAs.

**Comment by kevin-peng-hao** [comment]
Right, I got it. I mess it up with the non-secure world libraries. Sorry.
