### ISSUE TITLE
Enabling and disabling interrupts in example application

### ISSUE THREAD

**Issue by abditag2** [linaro-swg/optee_examples#19]
Hi,

I want to enable a secure interrupt and set the handler. As I understand, I have to do this inside the trusted application and I need to use these functions. My questions is how am I supposed to include these functions so that my TA compiles and runs? These functions are not present in any of the .h files in the /out/ folder. 

	itr_add(&ppi_handler);
	itr_enable(TEST_PPI_ID);

I would appreicate any help.

**Comment by etienne-lms** [comment]
hello @abditag2,

Indeed you cannot call `itr_add`/`itr_enable` from a trusted application, the same way you cannot enable and configure interrupts from a Linux userland application. In the Linux world you need a driver for that. In the TEE world, you will also need to implement the service in the privileged layer. And your interrupt handler will NEED to be implemented in the privileged layer, not in a trusted application.

Have a look at **optee_os/core/arch/arm/pta/interrupt_tests.c** for a example of such a pseudo TA that enables/catches interrupts.  Look at https://github.com/OP-TEE/optee_os/blob/master/documentation/optee_design.md#pseudo-tas-and-user-mode-tas for info on pseudo TAs: an easy way to implement secure kernel services and have it invoked by a trusted application.

That said, be aware that currently you cannot get a TA execution be scheduled from a secure interrupt event.

**Comment by etienne-lms** [comment]
Looks like @lorc already answered through https://github.com/OP-TEE/optee_os/issues/2190. Hope thing got more clear to you.

**Comment by abditag2** [comment]
@etienne-lms This was extremely useful! I really appreciate it. Thanks.

**Comment by abditag2** [comment]
Quick question, I managed to successfully write a pseudo TA and call all it from normal world the same way that I call a TA. 

However, when inside the PTA, I call `itr_add` and `itr_enable` I get the following error. Am I following the correct steps? I thought that inside PTA is op-tee kernel level and I can add_itr and enable_itr. Woudl appreciate any help.


`D/TC:0 tee_ta_init_pseudo_ta_session:293 Lookup pseudo TA 48d58475-3d5e-4202-a775-9785d20f78ae
D/TC:0 tee_ta_init_pseudo_ta_session:305 Open interrupt_tests.ta
D/TC:0 tee_ta_init_pseudo_ta_session:319 interrupt_tests.ta : 48d58475-3d5e-4202-a775-9785d20f78ae
E/TC:0 
E/TC:0 Core data-abort at address 0x0 (translation fault)
E/TC:0  esr 0x96000006  ttbr0 0x0e177000   ttbr1 0x00000000   cidr 0x0
E/TC:0  cpu #0          cpsr 0x60000104
E/TC:0  x0  0000000000000000 x1  0000000000000000
E/TC:0  x2  0000000000000000 x3  000000000e17b7b0
E/TC:0  x4  000000000e1115b8 x5  000000000e17b8e8
E/TC:0  x6  0000000000000090 x7  0000000000000000
E/TC:0  x8  00000000809f5000 x9  000000000e16b2f4
E/TC:0  x10 00000000400071c8 x11 00000000c2084dd1
E/TC:0  x12 000000000e140930 x13 0000000040002f80
E/TC:0  x14 00000000cafbddd5 x15 00000000ca62c1d6
E/TC:0  x16 000000000e10f2fc x17 0000000000000000
E/TC:0  x18 000000000e16a7ec x19 000000000e147110
E/TC:0  x20 000000000e17b7a8 x21 00000000ffff0006
E/TC:0  x22 000000000e16ba50 x23 000000000e17b8b0
E/TC:0  x24 0000000000000000 x25 000000000e16b9e0
E/TC:0  x26 000000000e17b8b0 x27 00000000ffffffff
E/TC:0  x28 000000000e17b8e8 x29 000000000e17b6c0
E/TC:0  x30 000000000e1115ec elr 000000000e114d68
E/TC:0  sp_el0 000000000e17b6c0
E/TC:0 Call stack:
E/TC:0  0x000000000e114d68
E/TC:0  0x000000000e1115e8
E/TC:0  0x000000000e103eb4
E/TC:0  0x000000000e1147b8
E/TC:0  0x000000000e1104a8
E/TC:0  0x000000000e10710c
E/TC:0  0x000000000e102948
E/TC:0 Panic 'unhandled pageable abort' at core/arch/arm/kernel/abort.c:665 <abort_handler>
E/TC:0 Call stack:
E/TC:0  0x000000000e109e8c
`.

**Comment by jforissier** [comment]
Hi @abditag2,

Looks like your code is trying to dereference a NULL pointer...
You can use `scripts/symbolize.py` to decode the stack dump.

**Comment by etienne-lms** [comment]
Doc entry point: https://github.com/OP-TEE/build/blob/master/docs/debug.md#3-abort-dumps-panics
Not obvious to found.

**Comment by jforissier** [comment]
@etienne-lms I agree, this doc should be in `optee_os`. I will create a PR.

**Comment by abditag2** [comment]
In `interrupts.c` , I added a print inside the function itr_init and compiled but never saw that print happening. 
```
void itr_init(struct itr_chip *chip)
{
	EMSG("[FARDIN}: itr inited.");
	itr_chip = chip;
}
```

I have a suspicion that maybe `itr_chip` variable is not set for the platforms that I am testing i.e. QEMU and rpi3. Is that true? 
I can see itr_init being called in various files called `core/arch/arm/plat-*` for different platforms but there is none for rpi3 or qemu. 

If not, can you point me to the file where int_init is called?

**Comment by jenswi-linaro** [comment]
For QEMU virt (ARMv7-A) `itr_init()` is called from `main_init_gic()`.

**Comment by etienne-lms** [comment]
For qemu,I think https://github.com/OP-TEE/optee_os/blob/b0961f98d94ddf4783a20b03b9fb4ff4b1b4b6b9/core/arch/arm/plat-vexpress/main.c#L119 is the place.

**Comment by abditag2** [comment]
hey guys. 

I have spent some time investigating this and I found out that in https://github.com/OP-TEE/optee_os/blob/9a6def2fc824b4135c1421d4c87209323c161680/core/arch/arm/kernel/generic_boot.c#L880
the function that is called is the dummy version in the same file https://github.com/OP-TEE/optee_os/blob/9a6def2fc824b4135c1421d4c87209323c161680/core/arch/arm/kernel/generic_boot.c#L87

Basically, the function that @etienne-lms mentioned above is never called and therefore GIC is not initialized. That is why I get a panic when I try to add interrupt in the pseudo-TA. 

I am clearly doing something wrong in initializing the project or build process. These are the step I do to make the QEMU run.

    mkdir -p $HOME/devel/optee
    cd $HOME/devel/optee
    repo init -u https://github.com/OP-TEE/manifest.git -m default.xml
    repo sync

    cd build
    make toolchains

and finally, from /build/ I run 

    make run

**Comment by jenswi-linaro** [comment]
GIC is initialized on QEMU virt v7, you can test it yourself by pressing space while in the secure uart terminal.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
