### ISSUE TITLE
Remote Attestation process/protocol for OP-TEE

### ISSUE THREAD

**Issue by cezane** [linaro-swg/optee_examples#26]
I do not know if this is the right place to ask, but I would like to know if OP-TEE provides some mechanism through which we can attest that some code is the real trusted code we are expecting for. 

Also, is there some capabilities related to devices identification in a way I can query or authenticate a specific device running OP-TEE?

A fast search on Internet did not return good information...

**Comment by jforissier** [comment]
Hi @cezane,

- Trusted apps are signed, so they won't execute if they have been tampered with.
- For device authentication, you may use a device-specific key to sign a challenge. If the signature verifies OK, it means you have be talking to the expected device.

**Comment by cezane** [comment]
Thank you, @jforissier . I was thinking about what I asked, because I read [in a presentation ](https://asokan.org/asokan/research/AsiaCCS-Attestation_Tutorial_v7.pdf) that Kinibi OS, which is another platform for TEE development with TrustZone, has such process (remote attestation). Regarding authentication, I agree with you. The challenge is the "device-specific key" generation/maintenance, in order to keep the "ecosystem" secure.
