### ISSUE TITLE
Got  TA panicked when executing "optee_example_secure_storage" binary.

### ISSUE THREAD

**Issue by rdhobi** [linaro-swg/optee_examples#29]
Hello,
I have compiled and run secure_storage exapmple. while executing "optee_example_secure_storage" binary, TA get panic. below is logs of same. Can anyone give me hint what is happening here?

> root@colibri-imx6ull:~# optee_example_secure_storage 
> Prepare session with the TAD/TC:0 tee_ta_init_pseudo_ta_session:274 Lookup pseudo TA f4e750bb-1437-4fbf-8785-8d3580c34994
> 
> D/TC:0 load_elf:842 Lookup user TA ELF f4e750bb-1437-4fbf-8785-8d3580c34994 (Secure Storage TA)
> D/TC:0 load_elf:842 Lookup user TA ELF f4e750bb-1437-4fbf-8785-8d3580c34994 (REE)
> D/TC:0 load_elf_from_store:810 ELF load address 0x103000
> D/TC:0 tee_ta_init_user_ta_session:1021 Processing relocations in f4e750bb-1437-4fbf-8785-8d3580c34994
> 
> Test on object "object#1"
> - CreF/TC:0 trace_syscall:128 syscall #42 (syscall_storage_obj_create)
> F/TC:0 trace_syscall:128 syscall #2 (syscall_panic)
> ate and load object in the TA secE/TC:0 
> E/TC:0 TA panicked with code 0xffff0001
> E/TC:0 Status of TA f4e750bb-1437-4fbf-8785-8d3580c34994 (0x9e061b98) (active)
> E/TC:0  arch: arm  load address: 0x103000 ctx-idr: 2
> E/TC:0  stack: 0x102000 4096
> E/TC:0  region 0: va 0x100000 pa 0x9e000000 size 0x1000 flags ---R-X 
> E/TC:0  region 1: va 0x102000 pa 0x9e113000 size 0x1000 flags rw-RW- 
> E/TC:0  region 2: va 0x103000 pa 0x9e100000 size 0x8000 flags r-x--- [0]
> E/TC:0  region 3: va 0x10b000 pa 0x9e108000 size 0xb000 flags rw---- [0]
> E/TC:0  region 4: va 0x200000 pa 0x9fe01000 size 0x3000 flags rw-RW- 
> E/TC:0  [0] f4e750bb-1437-4fbf-8785-8d3580c34994 @ 0x103000
> E/TC:0 Call stack:
> E/TC:0  0x00103b9c
> E/TC:0  0x001036c3
> E/TC:0  0x00103085
> E/TC:0  0x00103b57
> D/TC:0 user_ta_enter:312 tee_user_ta_enter: TA panicked with code 0xffff0001
> D/TC:0 tee_ta_invoke_command:625 Error: ffff3024 of 3
> ure storage
> D/TC:0 tee_ta_close_session:380 tee_ta_close_session(0x9e061bd8)
> D/TC:0 tee_ta_close_session:399 Destroy session
> Command WRITE_RAW failed: 0xffff3D/TC:0 tee_ta_close_session:425 Destroy TA ctx
> 024 / 3
> Command WRITE_RAW failed: 0xffff3024 / 3
> optee_example_secure_storage: Failed to create an object in the secure storage

**Comment by jforissier** [comment]
Hi @rdhobi,

It looks like the error is caused by https://github.com/OP-TEE/optee_os/commit/e091b079d91b04e03ed4c465d61d63e044539b09. I suppose the application should be modified. @etienne-lms?

**Comment by rdhobi** [comment]
@jforissier: Thanks for help. Can you please give me hint what are the changes required in TA?

**Comment by rdhobi** [comment]
@jforissier: Thanks for help. Can you please give me hint what are the changes required in TA?

**Comment by jforissier** [comment]
Please see https://github.com/OP-TEE/optee_test/commit/9811a80d. A similar change in `optee_examples_secure_storage` should work.

**Comment by rdhobi** [comment]
@jforissier : Latest code have these changes already. Any other hint?
@etienne-lms : I will try to find solution and propose changes.

**Comment by rdhobi** [comment]
@jforissier: Changes suggested by you worked. Thanks for help.
@etienne-lms: How do I submit patch?

**Comment by jbech-linaro** [comment]
@rdhobi , fork the git in question, create a local branch where you apply the fix, then send it as a pull request. For more details, please have a look [here](https://github.com/OP-TEE/optee_os/blob/master/documentation/github.md#contributing).
