### ISSUE TITLE
Can't build a hello_world example by build_ta.sh

### ISSUE THREAD

**Issue by huashizhoujielun** [linaro-swg/optee_examples#35]
I use the build_ta.sh script , and here the error:
`cc -o optee_example_hello_world main.o -lteec -L/home/kael/Desktop/devel/optee/optee_examples/optee_client/out/export/lib
/usr/bin/x86_64-linux-gnu-ld: cannot find -lteec
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'optee_example_hello_world' failed
make: *** [optee_example_hello_world] Error 1
Note: $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk not found, cannot clean TA
Note: TA_DEV_KIT_DIR=/home/kael/Desktop/devel/optee/optee_examples/optee_os/out/arm/export-ta_arm32
`

**Comment by jforissier** [comment]
Hi @huashizhoujielun,

What is `build_ta.sh`?

**Comment by huashizhoujielun** [comment]
@jforissier Well,sorry guys , i forgot to copy the script.
`# Path to the toolchain
export PATH=${ROOT}/toolchains/aarch32/bin:$PATH

# Path to the TA-DEV-KIT coming from optee_os
export TA_DEV_KIT_DIR=${ROOT}/optee_os/out/arm/export-ta_arm32

# Path to the client library (GP Client API)
export TEEC_EXPORT=${ROOT}/optee_client/out/export

export PLATFORM=vexpress
export PLATFORM_FLAVOR=qemu_virt

# Toolchain prefix for user space code (normal world)
HOST_CROSS_COMPILE=arm-linux-gnueabihf-
# Build the host application
cd $CURDIR/host
make CROSS_COMPILE=$HOST_CROSS_COMPILE $@

# Toolchain prefix for the Trusted Applications
TA_CROSS_COMPILE=arm-linux-gnueabihf-
# Build the Trusted Application
cd $CURDIR/ta
make CROSS_COMPILE=$TA_CROSS_COMPILE $@
`
i want to build a example TA by this script but it fail , and the error message just above.

**Comment by huashizhoujielun** [comment]
@jforissier Well,sorry guys, i forgot to copy the script.

``
#Path to the toolchain
export PATH=${ROOT}/toolchains/aarch32/bin:$PATH

#Path to the TA-DEV-KIT coming from optee_os
export TA_DEV_KIT_DIR=${ROOT}/optee_os/out/arm/export-ta_arm32

#Path to the client library (GP Client API)
export TEEC_EXPORT=${ROOT}/optee_client/out/export

export PLATFORM=vexpress
export PLATFORM_FLAVOR=qemu_virt

#Toolchain prefix for user space code (normal world)
HOST_CROSS_COMPILE=arm-linux-gnueabihf-
#Build the host application
cd $CURDIR/host
make CROSS_COMPILE=$HOST_CROSS_COMPILE $@

#Toolchain prefix for the Trusted Applications
TA_CROSS_COMPILE=arm-linux-gnueabihf-
#Build the Trusted Application
cd $CURDIR/ta
make CROSS_COMPILE=$TA_CROSS_COMPILE $@
``

**Comment by jforissier** [comment]
Have you built `optee_client` successfully before compiling the application? `$TEE_EXPORT/lib/libteec.so` should exist.

But wait: `-L/home/kael/Desktop/devel/optee/optee_examples/optee_client/out/export/lib` looks wrong, why `optee_examples/optee_client`?

**Comment by huashizhoujielun** [comment]
I copy that script from Internet.
I found the lib path but when run the script it show "skipping incompatible".
Maybe i should rebuild the whole project after finish my own TA.
Sorry for wasting your time to answer my question and i close the issue.
