### ISSUE TITLE
Error: unsafe header/library path used in cross-compilation: '-I/usr/include/openssl'

### ISSUE THREAD

**Issue by cezane** [linaro-swg/optee_examples#40]
I am am trying to use the OpenSSL functions in my client application, but I am receiving the following error:
> aarch64-buildroot-linux-gnu-gcc: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/include/openssl'

My CMakefiles.txt is like:
```cmake
project (keyvault C)

set (SRC host/main.c)
set (CRYPTO_DIR /usr/include/openssl)

add_executable (${PROJECT_NAME} ${SRC})

include_directories (${CRYPTO_DIR})

target_include_directories(${PROJECT_NAME}
			   PRIVATE ta/include
			   PRIVATE include)

target_link_libraries (${PROJECT_NAME} PRIVATE teec)

install (TARGETS ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_BINDIR})
```

And my CA (host) Makefile is like:
```makefile
CC      ?= $(CROSS_COMPILE)gcc
LD      ?= $(CROSS_COMPILE)ld
AR      ?= $(CROSS_COMPILE)ar
NM      ?= $(CROSS_COMPILE)nm
OBJCOPY ?= $(CROSS_COMPILE)objcopy
OBJDUMP ?= $(CROSS_COMPILE)objdump
READELF ?= $(CROSS_COMPILE)readelf

OBJS = main.o

CRYPTO_DIR = /usr/include/openssl

CFLAGS += -Wall -I../ta/include -I./include -I$(CRYPTO_DIR)
CFLAGS += -I$(TEEC_EXPORT)/include
LDADD += -lteec -L$(TEEC_EXPORT)/lib

BINARY = keyvault

.PHONY: all
all: $(BINARY)

$(BINARY): $(OBJS)
	$(CC) -o $@ $< $(LDADD)

.PHONY: clean
clean:
	rm -f $(OBJS) $(BINARY)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
```

If I change the openssl folder to `optee/out-br/host/aarch64-buildroot-linux-gnu/sysroot/usr/include/openssl`, I get `undefined reference` to the openssl functions. E.g.: 
>undefined reference to 'BN_new'        
>undefined reference to 'RSA_new'

Can anyone suggest something to solve this problem?

**Comment by jforissier** [comment]
Hi @cezane ,

I assume you are using OP-TEE's manifest.git/build.git projects.
- First, you probably don't need both a plain Makefile and a CMake file (`CMakeLists.txt`). The latter should be enough.
- Second, you should not need to add anything to `-I` for OpenSSL. No need for your `CRYPTO_DIR` variable at all. Use `#include <openssl/crypto.h>` etc. in your source code. OpenSSL is already selected in the buildroot config (generated in `common.mk`).
- Third, you need to link against libcrypto: add `PRIVATE crypto` to `target_link_libraries( ... )` in `CMakeLists.txt`.

You may use `optee_test/host/xtest` as an example (it does use OpenSSL). See `build/br-ext/package/optee_test`, too.
