### ISSUE TITLE
tee_user_ta_enter: TA panicked with code 0x0 when calling TEEC_CloseSession

### ISSUE THREAD

**Issue by cezane** [linaro-swg/optee_examples#41]
In CA, I have the following function to end session and context:
```c
void terminate_tee_session(struct ta_attrs *ta)
{
	TEEC_CloseSession(&ta->sess);
	TEEC_FinalizeContext(&ta->ctx);
}
```
In TA, this is the code responsible to close session:
```c
void TA_CloseSessionEntryPoint(void *session)
{
	struct rsa_session *sess;

	DMSG("Session %p: release session", session);
	sess = (struct rsa_session *)session;

	/* Release the session resources */
	TEE_FreeTransientObject(sess->key_handle);
	TEE_FreeOperation(sess->op_handle);
	TEE_Free(sess);
}
```
I am getting the following error:
> D/TC:? 0 tee_ta_close_session:380 tee_ta_close_session(0xe171630)
D/TC:? 0 tee_ta_close_session:399 Destroy session
D/TA:  TA_CloseSessionEntryPoint:180 Session 0x4001a090: release session
E/TC:? 0 
E/TC:? 0 TA panicked with code 0x0
E/TC:? 0 Status of TA 2bb620d9-3e83-463b-b261-987fa92c95ef (0xe1715d0) (active)
E/TC:? 0  arch: aarch64  load address: 0x40005000 ctx-idr: 2
E/TC:? 0  stack: 0x40004000 4096
E/TC:? 0  region 0: va 0x40000000 pa 0xe100000 size 0x2000 flags ---R-X 
E/TC:? 0  region 1: va 0x40002000 pa 0xe174000 size 0x1000 flags ---RW- 
E/TC:? 0  region 2: va 0x40004000 pa 0xe318000 size 0x1000 flags rw-RW- 
E/TC:? 0  region 3: va 0x40005000 pa 0xe300000 size 0xd000 flags r-x--- [0]
E/TC:? 0  region 4: va 0x40012000 pa 0xe30d000 size 0xb000 flags rw---- [0]
E/TC:? 0  [0] 2bb620d9-3e83-463b-b261-987fa92c95ef @ 0x40005000
E/TC:? 0 Call stack:
E/TC:? 0  0x0000000040007adc
E/TC:? 0  0x00000000400055c4
E/TC:? 0  0x0000000040009f2c
E/TC:? 0  0x000000000e102d1c
D/TC:? 0 unwind_stack_arm64:56 FP out of bounds 0
D/TC:? 0 user_ta_enter:312 tee_user_ta_enter: TA panicked with code 0x0
D/TC:? 0 tee_ta_close_session:425 Destroy TA ctx

Using gdb, I got this:
> TEEC_CloseSession (session=session@entry=0xfffffffffc40) at src/tee_client_api.c:547
547		if (!session)
(gdb) n
544	{
(gdb) n
551		if (ioctl(session->ctx->fd, TEE_IOC_CLOSE_SESSION, &arg))
(gdb) n
544	{
(gdb) n
550		arg.session = session->session_id;
(gdb) s
551		if (ioctl(session->ctx->fd, TEE_IOC_CLOSE_SESSION, &arg))
(gdb) s
ioctl () at ../sysdeps/unix/sysv/linux/aarch64/ioctl.S:23
23		mov	x8, #__NR_ioctl
(gdb) n
24		sxtw	x0, w0
(gdb) n
25		svc	#0x0
(gdb) n
26		cmn	x0, #4095
(gdb) s
27		b.cs	.Lsyscall_error
(gdb) n
28		ret

I tried to use the `symbolize.py` to get more help, but I am getting this error:
>python optee_os/scripts/symbolize.py -d out-br/build/optee_examples-1.0/keyvault/ta/out/*
E/TC:? 0  arch: aarch64  load address: 0x40005000 ctx-idr: 2
E/TC:? 0  stack: 0x40004000 4096
E/TC:? 0  region 0: va 0x40000000 pa 0xe100000 size 0x2000 flags ---R-X 
E/TC:? 0  region 1: va 0x40002000 pa 0xe174000 size 0x1000 flags ---RW- 
E/TC:? 0  region 2: va 0x40004000 pa 0xe318000 size 0x1000 flags rw-RW- 
E/TC:? 0  region 3: va 0x40005000 pa 0xe300000 size 0xd000 flags r-x--- [0]
E/TC:? 0  region 4: va 0x40012000 pa 0xe30d000 size 0xb000 flags rw---- [0]
E/TC:? 0  [0] 2bb620d9-3e83-463b-b261-987fa92c95ef @ 0x40005000
E/TC:? 0 Call stack:
E/TC:? 0  0x0000000040007adc
E/TC:? 0  0x00000000400055c4
E/TC:? 0  0x0000000040009f2c
E/TC:? 0  0x000000000e102d1c
D/TC:? 0 unwind_stack_arm64:56 FP out of bounds 0
D/TC:? 0 user_ta_enter:312 tee_user_ta_enter: TA panicked with code 0x0
D/TC:? 0 tee_ta_close_session:425 Destroy TA ctx
E/TC:? 0  arch: aarch64  load address: 0x40005000 ctx-idr: 2
E/TC:? 0  stack: 0x40004000 4096
E/TC:? 0  region 0: va 0x40000000 pa 0xe100000 size 0x2000 flags ---R-X 
E/TC:? 0  region 1: va 0x40002000 pa 0xe174000 size 0x1000 flags ---RW- 
E/TC:? 0  region 2: va 0x40004000 pa 0xe318000 size 0x1000 flags rw-RW- 
Traceback (most recent call last):
  File "optee_os/scripts/symbolize.py", line 436, in <module>
    main()
  File "optee_os/scripts/symbolize.py", line 432, in main
    symbolizer.write(line)
  File "optee_os/scripts/symbolize.py", line 391, in write
    elf_idx) +
  File "optee_os/scripts/symbolize.py", line 316, in sections_in_region
    self.read_sections(elf)
  File "optee_os/scripts/symbolize.py", line 289, in read_sections
    stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

For me, it does not make sense such error (TA panick) in `TEEC_CloseSession` calling. Any suggestion? Thanks in advance.

**Comment by jforissier** [comment]
The crash occurs in the TA, not in the CA, so you won't see anything with `gdb` on the CA side.
You may either run `gdb` on the TA (see here: https://github.com/OP-TEE/build/blob/master/docs/debug.md#15-debugging-ta), or indeed use the symbolize script and a few debug traces in the TA.

The error with `symbolize.py` is likely caused by not having the toolchain in your `$PATH`. The script needs `aarch64-linux-gnu-addr2line`, `aarch64-linux-gnu-objdump` etc. so try adding their location to your path. I have on my to-do list to produce better diagnostics when such an error occurs ;-)

**Comment by cezane** [comment]
Thank you for your suggestions, @jforissier .

I started the TA debugging, but it did not help much, because at some point I got the following message: "Cannot find bounds of current function". Here is the output of the debugging process:
> Breakpoint 1, tee_entry_std (smc_args=0xe14e5f0 <stack_thread+8176>)
    at core/arch/arm/tee/entry_std.c:498
498	{
(gdb) n
504		if (smc_args->a0 != OPTEE_SMC_CALL_WITH_ARG) {
(gdb) n
498	{
(gdb) n
504		if (smc_args->a0 != OPTEE_SMC_CALL_WITH_ARG) {
(gdb) n
498	{
(gdb) n
504		if (smc_args->a0 != OPTEE_SMC_CALL_WITH_ARG) {
(gdb) n
510		parg = (uint64_t)smc_args->a1 << 32 | smc_args->a2;
(gdb) n
513		if (core_pbuf_is(CORE_MEM_NSEC_SHM, parg,
(gdb) n
510		parg = (uint64_t)smc_args->a1 << 32 | smc_args->a2;
(gdb) n
513		if (core_pbuf_is(CORE_MEM_NSEC_SHM, parg,
(gdb) n
517			if (parg & SMALL_PAGE_MASK) {
(gdb) n
521			mobj = map_cmd_buffer(parg, &num_params);
(gdb) n
531		arg = mobj_get_va(mobj, 0);
(gdb) n
532		assert(arg && mobj_is_nonsec(mobj));
(gdb) n
535		thread_set_foreign_intr(true);
(gdb) b TA_CloseSessionEntryPoint
Function "TA_CloseSessionEntryPoint" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 3 (TA_CloseSessionEntryPoint) pending.
(gdb) n
536		switch (arg->cmd) {
(gdb) n
544			entry_invoke_command(smc_args, arg, num_params);
(gdb) n
541			entry_close_session(smc_args, arg, num_params);
(gdb) s
entry_close_session (smc_args=<optimized out>, num_params=<optimized out>, 
    arg=<optimized out>) at core/arch/arm/tee/entry_std.c:335
335		arg->ret_origin = TEE_ORIGIN_TEE;
(gdb) s
336		smc_args->a0 = OPTEE_SMC_RETURN_OK;
(gdb) n
tee_entry_std (smc_args=0xe14e5f0 <stack_thread+8176>)
    at core/arch/arm/tee/entry_std.c:560
560		mobj_free(mobj);
(gdb) n
561	}
(gdb) n
__thread_std_smc_entry (args=0xe14e5f0 <stack_thread+8176>)
    at core/arch/arm/kernel/thread.c:591
591		if (args->a0 == OPTEE_SMC_RETURN_OK) {
(gdb) n
592			struct thread_ctx *thr = threads + thread_get_id();
(gdb) n
594			tee_fs_rpc_cache_clear(&thr->tsd);
(gdb) n
595			if (!thread_prealloc_rpc_cache) {
(gdb) n
603	}
(gdb) n
thread_std_smc_entry () at core/arch/arm/kernel/thread_a64.S:192
192		load_xregs sp, THREAD_SMC_ARGS_X0, 20, 23
(gdb) n
193		add	sp, sp, #THREAD_SMC_ARGS_SIZE
(gdb) n
thread_std_smc_entry () at core/arch/arm/kernel/thread_a64.S:196
196		msr	daifset, #DAIFBIT_ALL
(gdb) n
197		bl	thread_get_tmp_sp
(gdb) n
198		mov	sp, x0
(gdb) n
thread_std_smc_entry () at core/arch/arm/kernel/thread_a64.S:200
200		bl	thread_state_free
(gdb) n
202		ldr	x0, =TEESMC_OPTEED_RETURN_CALL_DONE
(gdb) n
203		mov	x1, x20
(gdb) n
204		mov	x2, x21
(gdb) n
205		mov	x3, x22
(gdb) n
206		mov	x4, x23
(gdb) n
207		smc	#0
(gdb) n
0x000000000e026404 in ?? ()
(gdb) n
Cannot find bounds of current function
(gdb) n
Cannot find bounds of current function

I am deducting that `smc` stands for secure monitor call and this is the problem, but I do not know why.

**Comment by cezane** [comment]
@jforissier , I found the problem:
```c
TEE_FreeTransientObject (object=0x70470)
    at lib/libutee/tee_api_objects.c:224
224		if (object == TEE_HANDLE_NULL)
(gdb) n
220	{
(gdb) n
227		res = utee_cryp_obj_get_info((unsigned long)object, &info);
(gdb) n
228		if (res != TEE_SUCCESS)
(gdb) n
231		if ((info.handleFlags & TEE_HANDLE_FLAG_PERSISTENT) != 0)
(gdb) n
234		res = utee_cryp_obj_close((unsigned long)object);
(gdb) n
235		if (res != TEE_SUCCESS)
(gdb) n
237	}
(gdb) n
TA_CloseSessionEntryPoint (session=0x4001a090) at keyvault.c:185
185		TEE_FreeOperation(sess->op_handle);
4: sess->key_handle = (TEE_ObjectHandle) 0x70470
5: sess = (struct rsa_session *) 0x4001a090
6: session = (void *) 0x4001a090
(gdb) s
TEE_FreeOperation (operation=0x0 <ta_head>)
    at lib/libutee/tee_api_operations.c:344
344	{
(gdb) n
347		if (operation == TEE_HANDLE_NULL)
(gdb) n
348			TEE_Panic(0);
(gdb) n
```

Can you explain me, please, the necessity of a panic when `operation == TEE_HANDLE_NULL`? What is the problem when freeing a `TEE_HANDLE_NULL` reference? I think it is simpler just do nothing if this condition is true and free the `operation` otherwise. Please correct me if I wrong with this thought.

**Comment by jbech-linaro** [comment]
The panic there comes from the TEE Internal API spec. See the panic conditions for the TEE_FreeOperation in the spec.

**Comment by cezane** [comment]
Thank you again, @jbech-linaro and @jforissier .

Indeed, the specification mentions the following panic reasons:
-  operation is not a valid handle on an operation.
-  If the Implementation detects any other error.

But, in my humble opinion, I think `valid handle` could have two meanings:
- One considering the content of the handle, i.e. an operation initialized, that is not null (this is how it is implemented);
- Another considering the type of the handle, being enough validation only regarding type (valid type: `TEE_OperationHandle`), and, thus, accepting "null handles".

I think this second approach would be better, avoiding the need to test if the variable is not null before call `TEE_FreeOperation`.

**Comment by jforissier** [comment]
@cezane I agree. The good news is: the upcoming Internal Core API Specification v1.2 clarifies the behavior and explicitly allow a null value. It states: "The function does nothing if operation is TEE_HANDLE_NULL [...] Backward Compatibility. Prior to TEE Internal Core API v1.2, TEE_FreeOperation MAY Panic if operation is TEE_HANDLE_NULL."
 
:)
