### ISSUE TITLE
KeyDerive demo

### ISSUE THREAD

**Issue by guojuntang** [linaro-swg/optee_examples#42]
Hi,sir.
Recently i make a DH demo for optee.
When i run that demo ,the value of private key and public key are both correct but it give me a wrong result when calculating the shared secret.
Here uploaded the source code as attach.
In the demo i set a small prime and base ,and output some value for debugging.

Thanks!
[dh.zip](https://github.com/linaro-swg/optee_examples/files/2383742/dh.zip)

**Comment by 2cute2die** [comment]
@huashizhoujielun : any updates on the DH Key Exchange TA. I'm very interested in the TA too and try to debug it right now. So far no success. Did you find the cause of the mismatching shared secrets?

**Comment by huashizhoujielun** [comment]
@2cute2die : Hi , I have solved that by replacing the prime number.

`	unsigned char prime[PRIME_TEST_LENGTH] ={0x50,0xf6,0x30,0x58,0x6d,0x9a,0x23,0x6d,0xf0,0x4b,0xf5,0xcc,0xab,0xab,0xd9,0xf6,0x6a,0x05,0x60,0xe2,0x2c,0x37,0x8e,0x56,0x0a,0x52,0xa1,0xdd,0x6c,0xbc,0xa5,0x0b};
	unsigned char base[BASE_TEST_LENGTH] = {0x02};`
And the other parts are available in uploaded zip file. 

Seem it will mismatch the shared secret if take a small number as prime.
