### ISSUE TITLE
Running sample examples on Raspberry Pi 3.

### ISSUE THREAD

**Issue by Gerryyq** [linaro-swg/optee_examples#46]
Hi, how should I go about getting the sample applications into my Raspberry Pi and executing the application?
I've gotten the OPTEE running on my Raspberry Pi 3 via cross compilation and a custom buildroot, as the xtest works fine. However, I'm quite clueless on how to go about trying the samples, before I try to write my own simple TA. 

I've seen the slides from https://www.slideshare.net/linaroorg/lcu14103-how-to-create-and-run-trusted-applications-on-optee, but it just doesn't speak to me. Would be grateful if anyone knows how. 

 Thanks in advance!

**Comment by jbech-linaro** [comment]
Great! Seems like you're happy with my reply, so I'll go a head and close this issue (you can always re-open or create another issue if you have additional questions), thanks!
