### ISSUE TITLE
Storing generated values within TA.

### ISSUE THREAD

**Issue by Gerryyq** [linaro-swg/optee_examples#52]
Hi,

I'm trying to incorporate `TEE_GenerateRandom` in my sample TA, on RPI3. I understand that `TEE_GenerateRandom` returns void, and generates a random UUID by changing the values passed by reference, allowing the CA to print out the generated value.
However, I wish to store the generated value within my TA, and not at CA, is that possible? As I wish to encrypt the value within TA later.  I hope I'm speaking with a bit of sense here.
Would appreciate any help! Thanks! 

P.S. I couldn't find any `TEE_GenerateRandom` function within `tee_api.c`, only found it in `tee_api.h` file, so I'm not certain how the function actually works.

**Comment by jforissier** [comment]
Hi @Gerryyq,

`TEE_GenerateRandom()` produces random bytes, not specifically a UUID. The value is returned to the calling TA into whatever buffer the TA has passed to the function. Doesn't have to be a buffer that comes from the CA. You could allocate the buffer with `TEE_Malloc()`, or define it as a global variable. For instance:

```
unsigned char rnd[10];

TEE_Result TA_OpenSessionEntryPoint(...)
{
        TEE_GenerateRandom(rnd, sizeof(rnd));
        ....
}
```

`TEE_GenerateRandom()` is in `lib/libutee/tee_api_operations.c` but the implementation is actually in the TEE core (entered via `syscall_cryp_random_number_generate()`).

```
$ git grep TEE_GenerateRandom
lib/libutee/include/tee_api.h:void TEE_GenerateRandom(void *randomBuffer, uint32_t randomBufferLen);
lib/libutee/tee_api_operations.c:void TEE_GenerateRandom(void *randomBuffer, uint32_t randomBufferLen)
lib/libutee/tee_api_operations.c:       TEE_GenerateRandom(&rc, sizeof(rc));
```

**Comment by Gerryyq** [comment]
> Hi @Gerryyq,
> 
> `TEE_GenerateRandom()` produces random bytes, not specifically a UUID. The value is returned to the calling TA into whatever buffer the TA has passed to the function. Doesn't have to be a buffer that comes from the CA. You could allocate the buffer with `TEE_Malloc()`, or define it as a global variable. For instance:
> 
> ```
> unsigned char rnd[10];
> 
> TEE_Result TA_OpenSessionEntryPoint(...)
> {
>         TEE_GenerateRandom(rnd, sizeof(rnd));
>         ....
> }
> ```
> `TEE_GenerateRandom()` is in `lib/libutee/tee_api_operations.c` but the implementation is actually in the TEE core (entered via `syscall_cryp_random_number_generate()`).
> 
> ```
> $ git grep TEE_GenerateRandom
> lib/libutee/include/tee_api.h:void TEE_GenerateRandom(void *randomBuffer, uint32_t randomBufferLen);
> lib/libutee/tee_api_operations.c:void TEE_GenerateRandom(void *randomBuffer, uint32_t randomBufferLen)
> lib/libutee/tee_api_operations.c:       TEE_GenerateRandom(&rc, sizeof(rc));
> ```

Hi @jforissier ,

Thank you for your swift reply!! 
I'll look into it and try it out!!
For now I'll close this thread!
Cheers! (:

**Comment by Gerryyq** [comment]
> Hi @Gerryyq,
> 
> `TEE_GenerateRandom()` produces random bytes, not specifically a UUID. The value is returned to the calling TA into whatever buffer the TA has passed to the function. Doesn't have to be a buffer that comes from the CA. You could allocate the buffer with `TEE_Malloc()`, or define it as a global variable. For instance:
> 
> ```
> unsigned char rnd[10];
> 
> TEE_Result TA_OpenSessionEntryPoint(...)
> {
>         TEE_GenerateRandom(rnd, sizeof(rnd));
>         ....
> }
> ```
> 
> `TEE_GenerateRandom()` is in `lib/libutee/tee_api_operations.c` but the implementation is actually in the TEE core (entered via `syscall_cryp_random_number_generate()`).
> 
> ```
> $ git grep TEE_GenerateRandom
> lib/libutee/include/tee_api.h:void TEE_GenerateRandom(void *randomBuffer, uint32_t randomBufferLen);
> lib/libutee/tee_api_operations.c:void TEE_GenerateRandom(void *randomBuffer, uint32_t randomBufferLen)
> lib/libutee/tee_api_operations.c:       TEE_GenerateRandom(&rc, sizeof(rc));
> ```

Hi @jforissier ,

As you mentioned, I've tried using `TEE_GenerateRandom()` directly, however, I'm quite clueless as to how to get it displaying different legible characters each time. While displaying as hexadecimal, always return me the same value.
Below are snippets of my code & results.
```
        unsigned char rng[10];
	TEE_GenerateRandom(rng, sizeof(rng));
	printf("\nSample char = 0x %c \n", rng);
	printf("\nSample string = 0x %s \n", rng);
	printf("\nSample hexa = 0x %x \n", rng);
	printf("\nSAMPLE RANDOM = ");
	printf(rng);
        printf("\n");
```
![screenshot from 2019-02-16 18-42-16](https://user-images.githubusercontent.com/32240805/52898673-500c4d00-321b-11e9-8b1b-3cd478aaf164.png)

**Comment by jforissier** [comment]
You need a loop
https://stackoverflow.com/questions/10375932/printing-the-hexadecimal-representation-of-a-char-array

**Comment by Gerryyq** [comment]
> You need a loop
> https://stackoverflow.com/questions/10375932/printing-the-hexadecimal-representation-of-a-char-array

Got it, thank you! :+1:
