### ISSUE TITLE
Can't find optee_example_ files when run the examples

### ISSUE THREAD

**Issue by tulipper** [linaro-swg/optee_examples#58]
Hello there!
I built OPTEE+AOSP in my hikey960 refering to [https://optee.readthedocs.io/building/aosp/aosp.html](url)
and xtest and optee_examples_* works well. 
Then I build the  standalone examples according to [https://github.com/linaro-swg/hello_world](url) , after that  I use adb to push the host application and the .ta to /vendor/bin and /vendor/lib/optee_armtz/ respectively where the xtest and other .ta files locates. 
when I run optee_example _helloworld, it can't find the optee_example_helloworld but it does exist.
`/system/bin/sh: /vendor/bin/optee_example_hello_world: No such file or directory`
Then I compare the two files (the one build manually and the one pull from the board) and find they are quite different:
`$ file optee_example_random
optee_example_random: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.7.0, with debug_info, not stripped`
`$ file optee_example_random_arm 
optee_example_random_arm: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /system/, BuildID[md5/uuid]=3efe792d5b4270c901489624d9dff1ea, stripped`
the arm one is pull from the board. 
is the build instruction not suitable for the AOSP? or some other reason?
and how to build the examples suitable for the AOSP?
Thanks for any suggestions.

**Comment by jbech-linaro** [comment]
Don't build externally when working with AOSP, i..e, only do builds using the AOSP makefiles etc. So, either a plain `make` from the top of the tree, alternatively cd into `external/optee_examples` and run `mm` (after doing `.source build/envsetup.sh &&  lunch hikey960-userdebug`). After that you can `adb push` the files (replace names with accordingly to other example TA's).
```bash
adb push out/target/product/hikey/symbols/vendor/bin/optee_example_hello_world /vendor/bin/
adb push out/target/product/hikey/optee/ta/external_optee_examples_hello_world_ta/8aaaf200-2450-11e4-abe2-0002a5d5c51b.ta  /vendor/lib/optee_armtz/
```

@vchong , I'm correct here I guess?

**Comment by jbech-linaro** [comment]
> @vchong , I'm correct here I guess?

I can answer myself after just trying this ... yes, this works :)

**Comment by jbech-linaro** [comment]
Even better, just after rebuilding, run:
```bash
$ adb sync
```
And it will do the updates for you. I.e., you don't have to figure out where to get files and where to push files.

**Comment by tulipper** [comment]
the mm or the mmm command does not work correctlly in my trying, but I can run the command reference to [https://github.com/OP-TEE/optee_os/issues/2920](url)
`./build.sh -v p -t hikey960 optee_example_hello_world` 
so it is OK to build in one way. 
I think the method of build the example in aosp+optee is different from that in the separate optee build. I guess the latter use the Aarch-linux-gnu-eabi- toolchains while the former may use the ndk-build or the android-linux-androideabi. because the the linux console application is quite different from the android console application. Does it make sense? @jbech-linaro

**Comment by jbech-linaro** [comment]
> the mm or the mmm command does not work correctlly in my trying

What's the error message then? I've done more or less the same as you have. I.e., I've used `build.sh` to get the "p-release". Then after that I've just done (note I'm using HiKey not HiKey960, but the way it's done should be the same).
```bash
$ source build/envsetup.sh
$ lunch hikey-userdebug
```

> I think the method of build the example in aosp+optee is different  ... because the the linux console application is quite different from the android console application. Does it make sense?

Right and that's the reason I recommended to just build from AOSP directly.

**Comment by tulipper** [comment]
[logcat.txt](https://github.com/linaro-swg/optee_examples/files/3210777/logcat.txt)
This logcat file log what I have input and what the console display. I have rebuilt the whole project before doing the command above, so there should not be so many files to process. May be I missed something.

**Comment by jbech-linaro** [comment]
> May be I missed something.

Yes, I fixed that a couple of days ago :) See https://github.com/linaro-swg/optee_examples/pull/59 (now merged). So if you checkout tip of master on optee_examples, then it should work.

**Comment by vchong** [comment]
> @vchong , I'm correct here I guess?

Yes. `out/target/product/hikey/symbols/vendor/bin/optee_example_hello_world` is the non-stripped binary. For the stripped, `out/target/product/hikey/vendor/bin/optee_example_hello_world` can be used.

> the mm or the mmm command does not work correctlly in my trying

Overall, if you're using the `optee_android_manifest` build scripts, please try to stick to using `build*.sh <options> <build target>` and avoid using `mm` and friends. Most build targets should work with `mm` and friends, but a few of them depends on variables exported by the build scripts which are not be defined when running `mm` and friends.

Closing this now. Please submit new issue if necessary.
