### ISSUE TITLE
TA in secure world access the resource in normal world

### ISSUE THREAD

**Issue by Tigerly** [linaro-swg/optee_examples#6]
Hello everyone,
According to the TEE document, it seems that the secure world has the highest authority and it can access all the resource in the normal world. Is it correct for op-tee?

I'm curious about if I run a program in the normal world, sending a variable's address (pointer) to the TA in the secure world via TEE APIs. Can TA directly access this variable which is in the normal world?

Thanks in advance!

**Comment by jbech-linaro** [comment]
Hi Tigerly,

Yes, secure side is the highest authority and what you are saying is kind of true (although different TEE implementations are setting certain limits). In fact there is a paper about it published not that long ago. Some TEE vendors are doing better than other (OP-TEE is probably doing better at least according to the researchers writing the paper).


There is a presentation about it also at YouTube:
https://youtu.be/_4hMO36NPSg

OP-TEE mentions:
https://youtu.be/_4hMO36NPSg?t=7m4s
https://youtu.be/_4hMO36NPSg?t=11m45s
https://youtu.be/_4hMO36NPSg?t=14m42s

And paper, code etc are here:
https://github.com/ucsb-seclab/boomerang

// Joakim

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
