### ISSUE TITLE
Crypto TA example for Linux

### ISSUE THREAD

**Issue by jonsmirl** [linaro-swg/optee_examples#60]
What do you think about moving kmgk under optee_examples? Then you can make a host directory containing Linux code which would not impact the Android code. 

There is no rule that Linux crypto has to use PKCS#11.  For the most common use case an OpenSSL plug-in could load the existing keymaster TA and use it to do the initial ECC exchange for the IOT services -- AWS, Google, Azure, Baidu.

The needed code is already in AOSP, it just need to be de-Androidized. 
https://android.googlesource.com/platform/system/security/+/refs/heads/master

keystore-engine is the SSL plug in
keystore is the Android daemon

Code from those two projects could be merge into a single OpenSSL plug-in under Linux - no need for a daemon. This doesn't work multi-user, but embedded systems aren't multiuser.

**Comment by vchong** [comment]
I don't know if others might disagree, but perhaps the `host` and `ta` don't have to live under the same repo, and you can maybe submit a PR for the linux host of the kmgk ta here?

In any case, the long term plan for the kmgk repo is for the (aosp) host to be upstreamed to aosp if possible, and the ta to be upstreamed to aosp and/or optee_os, so the repo itself won't be there in the future if all goes to plan.

**Comment by jbech-linaro** [comment]
The goal with optee_examples was to create minimal host/ta pairs. I.e., as little code as possible to talk the TEE and doing as "little as possible" in the TA. I.e., in the past we got many questions like "How do I generate a hash with GP interfaces", "How do I store files with secure storage", "How to I generate a random number" and so on. These are the types of things that can be expected to be found in optee_examples.

KMGK is a full implementation of an entire AOSP API, i.e., it doesn't belong in optee_examples. It belongs at a) upstream in AOSP and b) in [optee_os/ta](https://github.com/OP-TEE/optee_os/tree/master/ta) as a service TA implementing some real API.

As @vchong mentioned we're working with Google trying to get the stuff merged upstream in the AOSP tree. Hopefully that gets resolved in a foreseeable future.
