### ISSUE TITLE
-Wl,--wrap with TA

### ISSUE THREAD

**Issue by divneil** [linaro-swg/optee_examples#66]
Hi,

I am trying to add some test cases to my TA by using `-Wl,--wrap` for few of the functions like `malloc()`. However, I end up with the following compilation error. Can you please help:

In TA, I will move to `TEE_Malloc()`, but just trying to get the basic compilation working using `malloc()`.

```
..../hello_world/ta/hello_world_ta.c:38: undefined reference to `__real_malloc'
```

Reference code: `hello_world_ta.c`
```c
void *__real_malloc(size_t size);
void *__wrap_malloc (size_t size);
void *__wrap_malloc (size_t size)
{
	void *ptr = __real_malloc(size);
      	IMSG("malloc(%ld) = %p\n", size, ptr);
       	return ptr;
}
#endif
```
`ta/sub.mk`

```
cflags-hello_world_ta.c-y += -Wl,--wrap,malloc
```

Regards,
Divneil

**Comment by jforissier** [comment]
Hi @divneil,

Have you resolved this issue? I think the link fails because you're adding the `-wl,--wrap,malloc` option at the wrong place. Try this:

```diff
diff --git a/hello_world/ta/Makefile b/hello_world/ta/Makefile
index 3d2e6fc..3d6837e 100644
--- a/hello_world/ta/Makefile
+++ b/hello_world/ta/Makefile
@@ -4,6 +4,7 @@ CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)
 # The UUID for the Trusted Application
 BINARY=8aaaf200-2450-11e4-abe2-0002a5d5c51b

+link-ldflagsta_arm32 = --wrap malloc
 -include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk

 ifeq ($(wildcard $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk), )
```

(replace `link-ldflagsta_arm32` with `link-ldflagsta_arm64` if you're building 64-bit TAs)

**Comment by divneil** [comment]
Hi @jforissier 

> Have you resolved this issue? I think the link fails because you're adding the `-wl,--wrap,malloc` option at the wrong place. Try this:

Thanks. It works out for me now. I was unable to figure out the flag name. Is it possible to post this in `optee_examples/docs/TA_basics.md`.

**Comment by jforissier** [comment]
> I was unable to figure out the flag name.

Perhaps we could add a new variable called `$(user-ta-ldflags)`, similar to `$(user-ta-ldadd)` (see 
`ta/arch/arm/link.mk`). It would help set flags that are not dependent on the architecture (32 vs. 64-bit), which is the case here.

```diff
index 247d45b9..e50af7ff 100644
--- a/ta/arch/arm/link.mk
+++ b/ta/arch/arm/link.mk
@@ -22,6 +22,7 @@ link-ldflags += --sort-section=alignment
 link-ldflags += -z max-page-size=4096 # OP-TEE always uses 4K alignment
 link-ldflags += --as-needed # Do not add dependency on unused shlib
 link-ldflags += $(link-ldflags$(sm))
+link-ldflags += $(user-ta-ldflags)
 
 ifeq ($(CFG_FTRACE_SUPPORT),y)
 $(link-out-dir$(sm))/dyn_list:
```

>  Is it possible to post this in `optee_examples/docs/TA_basics.md`.

Yep, patch(es) welcome ;-)

**Comment by divneil** [comment]
> Yep, patch(es) welcome ;-)

You already posted the patch :). Just one liner in `TA_basics.md` is pending.
