### ISSUE TITLE
Implicit declaration of system function

### ISSUE THREAD

**Issue by varsha-2508** [linaro-swg/optee_examples#72]
I figured that the hello world example increments a number. Instead of incrementing a number, I wanted my TA to do a wget to some website. So I added a system("wget website") to my code along with the necessary header file, stdlib.h. 
But when I run make, it always shows implicit declaration of system function.  Could you please help?

**Comment by etienne-lms** [comment]
Indeed `system()` standard function and the related syscall is not implemented in optee_os and even to considered in optee architecture. Also these is not `wget` trusted application your TA could rely on. What you could do is maybe to have non-secure world (i.e. Linux OS) performing the wget operation and pass the fetched binary to your TA, but such a process would rely on non-secure world network stack which may or may not be an issue, depending on your expectations. Having a full secure network stack is something currently not supported in OP-TEE.

**Comment by varsha-2508** [comment]
Thank you for your reply. I understand that opening a socket connection from within the secure world is possible. What I want to do is I want to open a connection to the cloud and pass some readings to it. Can I do this inside the TEE? 
Thanks for the help in advance!
