### ISSUE TITLE
Adding New client application to the optee_examples

### ISSUE THREAD

**Issue by Noufalp90** [linaro-swg/optee_examples#74]
Hi Team, 
I would like to add a new custom client application to the optee_example/ directory (`optee_android_manifest/external/optee_examples`) and build along with the AOSP source code. The client application is to access custom Pseudo Trusted Application developed by me. Now am concentrating on bringing up client application and then Pseudo application. Can anyone please help the steps to be followed to do the same? 

I have added a folder under `optee_android_manifest/external/optee_examples/custom_client/` and follwoing are the contents. 
```
CMakeLists.txt  
custom_client_pta.h 
main.c

```

**Comment by etienne-lms** [comment]
This looks ok to build a host application (aka a non-secure Linux application) that invokes trusted services (TA or PTA).
If for a PTA, indeed PTA implementation shall be in optee_os source file tree.
