### ISSUE TITLE
cannot find -lteec

### ISSUE THREAD

**Issue by B1nd00** [linaro-swg/optee_examples#97]
I'm building op-tee on qemu with Armv8 and I've built optee_os and optee_client. I'm unable to make the example files as it returns the error cannot find -lteec.

This is what I do before make
` export HOST_CROSS_COMPILE=/User_data/home/nramu/optee-qemuv8-3.14.0/toolchains/aarch64/bin/aarch64-linux-gnu-`
`export TA_CROSS_COMPILE=/User_data/home/nramu/optee-qemuv8-3.14.0/toolchains/aarch32/bin/arm-linux-gnueabihf-`
`export TEEC_EXPORT=/User_data/home/nramu/optee-qemuv8-3.14.0/optee_client/out/export`
`export TA_DEV_KIT_DIR=/User_data/home/nramu/optee-qemuv8-3.14.0/optee_os/out/arm/export-ta_arm32/`

And this is my error
![image](https://user-images.githubusercontent.com/92019928/181308721-511f65d2-33cb-46cd-ab1d-87bc02254723.png)

If I do the make individually, the ta compiles not the host

**Comment by etienne-lms** [comment]
Looking a _acipher/host/Makefile_, your should get `-L$(TEEC_EXPORT)/lib` next to `-lteec` at linker invocation.
```makefile
LDADD += -lteec -L$(TEEC_EXPORT)/lib
(...)
$(BINARY): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $< $(LDADD)
```
Maybe try to add some traces in the Makefile to understand which arguments are passed to gcc.

**Comment by B1nd00** [comment]
Yes I am getting that. I switched i

> Looking a _acipher/host/Makefile_, your should get `-L$(TEEC_EXPORT)/lib` next to `-lteec` at linker invocation.
> 
> ```makefile
> LDADD += -lteec -L$(TEEC_EXPORT)/lib
> (...)
> $(BINARY): $(OBJS)
> 	$(CC) $(LDFLAGS) -o $@ $< $(LDADD)
> ```
> 
> Maybe try to add some traces in the Makefile to understand which arguments are passed to gcc.

I am getting that! It was the wrong image for the output. My bad
